# Generated by Django 5.1.4 on 2024-12-08 12:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('missingperson', '0002_remove_missingperson_identification_marks'),
    ]

    operations = [
        migrations.AddField(
            model_name='missingperson',
            name='approval',
            field=models.CharField(choices=[('Approved', 'Approved'), ('Rejected', 'Rejected'), ('Pending', 'Pending')], default='Pending', max_length=10),
        ),
        migrations.AddField(
            model_name='missingperson',
            name='status',
            field=models.CharField(choices=[('Missing', 'Missing'), ('Found', 'Found')], default='Missing', max_length=10),
        ),
        migrations.AlterField(
            model_name='location',
            name='missing_person',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='locations', to='missingperson.missingperson'),
        ),
    ]
